### ISSUE TITLE
这个镜像里面是不是没有装npm？

### ISSUE THREAD

**Issue by cuiyao50** [phvia/dkc#12]
Service 'fe' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y nodejs     && npm install -g webpack && npm install -g vue-cli' returned a non-zero code: 127，我在装的时候报了这个错误，你看是不是镜像里没有转npm

**Comment by farwish** [comment]
@cuiyao50  项目在 Ubuntu16.04 上总是能够 build 通过并运行，你的宿主机是什么系统和什么版本，还有中途有没有其它操作之类？
